name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: action/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew build

    - name: list files
      run: ls -lrt app/build/outputs/apk/debug

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: 1
        token: ${{secrets.TESTE_ACTION_GITHUB}}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk