name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Android version
        id: get_version
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: ${{ steps.get_version.outputs.versionName }}