name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-debug.apk
#          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload QA Flavour APK to Firebase App Tester
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1
          serviceCredentialsFileContent: ${{ secrets.TESTE_ACTION_GITHUB }}
          groups: group-test
          releaseNotes: ${{ github.event.head_commit.message }}
          file: app/build/outputs/apk/debug/app-debug.apk