name: Android Build

on:
  pull_request:
    branches: main

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: get commit message
        run: | 
            echo Commit MSG = ${{ env.commitmsg }}

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: ${{ env.commitmsg }}
          file: app/build/outputs/apk/debug/app-debug.apk