name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1

      - name: Build Project
        run: ./gradlew assemble